### ISSUE TITLE
[Enhence?] px to rem

### ISSUE THREAD

**Issue by hd1534** [SSU-DokTalk/doktalk-fe#34]
```css
html {
  font-size: 14px;
}

@media (min-width: 400px) {
  html {
    font-size: 16px;
  }
}
```

를 적용해서 rem을 사용하는게 좀 더 편리함
